
api_key: OEsQisxnXRnBT4Kgj3mBhK64L3E9nymV
convert_url: https://api.apilayer.com/exchangerates_data/convert?to=%s&from=%s&amount=%s
fluctuate_url: https://api.apilayer.com/exchangerates_data/fluctuation?start_date=%s&end_date=%s
kafka_topic: currency-topic
kafka_server_url: localhost:9092
interval: 10
topic_api_url: https://api.apilayer.com/exchangerates_data/convert?to=INR&from=EUR&amount=1

